volumes:
    grafana_data: {}
    clickhouse_data: {}

networks:
  gigapipe-oss:
    driver: bridge

services:
  grafana:
    image: grafana/grafana-oss:11.5.0
    container_name: grafana
    networks:
      - gigapipe-oss
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_EXPLORE_ENABLED=true
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - gigapipe
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  clickhouse-server:
    image: clickhouse/clickhouse-server:24.9.1-alpine
    container_name: clickhouse-server
    hostname: clickhouse
    restart: unless-stopped
    networks:
      - gigapipe-oss
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=gigapipe
      - CLICKHOUSE_PASSWORD=123456
    ports:
      - 8123:8123
      - 9000:9000
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', '127.0.0.1:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  gigapipe:
    image: ghcr.io/metrico/gigapipe:latest
    container_name: gigapipe
    hostname: gigapipe
    pull_policy: always
    restart: unless-stopped
    networks:
      - gigapipe-oss
    expose:
      - 3100
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse-server
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_AUTH=gigapipe:123456
      - CLICKHOUSE_DB=qryn
      - PORT=3100
      - NODE_OPTIONS="--max-old-space-size=4096"
      - FASTIFY_METRICS=true
    depends_on:
      clickhouse-server:
        condition: service_healthy
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"
      
  otel-collector:
    container_name: otel-collector
    hostname: otel-collector
    image: ghcr.io/metrico/qryn-otel-collector:latest
    networks:
      - gigapipe-oss
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel/config.yaml
    ports:
      - "3200:3100"     # Loki/Logql HTTP receiver
      - "3201:3200"     # Loki/Logql gRPC receiver
    restart: on-failure
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    restart: unless-stopped
    networks:
      - gigapipe-oss
    volumes:
      - ./vector/vector_demo.yaml:/etc/vector/vector.yaml:ro # demo vector config with syslog
    depends_on:
      - gigapipe
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

